name: WOMPRO
favicon: null
layout_spectrum: 0.023311475524678826
typography_spectrum: 0.9138825573027134
title: Promo stuff
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e51837'
    - '#013668'
    - '#b1c4d6'
    - '#6f88a6'
  brandStrength: 0.3246640295255929
  lightness: 0.7899249652400613
  saturation: 0.2437166958115995
  rhythmicContrast: 0.75
purpose: []
