name: WOMPRO
favicon: null
layout_spectrum: 0.023311475524678826
typography_spectrum: 0.9138825573027134
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.3246640295255929
  lightness: 0.7899249652400613
  saturation: 0.2437166958115995
  rhythmicContrast: 0.5948256577830762
purpose: []
